export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";
export const SORT_BY = "SORT_BY";
export const FETCH_SONGS_SUCCESS = 'FETCH_SONGS_SUCCESS';
export const FETCH_SONGS_FAILURE = 'FETCH_SONGS_FAILURE';
